export default {
  lugaresInfo: [
    'El PedWest (Pedestrian West) es una nueva forma de cruzar de Tijuana a San Ysidro por la via peatonal, actualmente cuenta con catorce líneas de inspección para procesar al público general, así como usuarios de los programas Ready Lane y SENTRI.  Este nuevo acceso se encuentra por la Plaza Viva Tijuana o la Plaza de Artesanías ubicada en el centro de Tijuana.',
    'Con mas de 40 años, en este mercado se puede encontrar  la más completa variedad de artesanías y materiales para la decoración del hogar, la mayoria elaboradas por artesanos locales.  Al ingresar al mismo encontrarás amplios y vistosos callejones con los nombres de  poblados representativos de nuestro país: “Cholula”,  “Andador Tlaquepaque”, “Callejón San Miguel”. En estos es posible encontrar pinturas, artesanía miniatura, herrería, cerámica, madera, productos de piel, textiles, vidrio soplado, puertas, imágenes en piedra, cemento, barro y yeso de culturas prehispánicas. Además, aqui se puede adquirir mueblería rústica de muy alta calidad, juguetes diversos , diminutas figuras de vidrio soplado, dulces, fotografías de personajes como Frida Kahlo o Pancho Villa, y más.',
    'Inaugurado en 1993, el museo cuenta con 86 figuras clasificadas por temas como lo son la sala de historia de México, Sala de Estadistas (Grandes Líderes del siglo XX) Sala de artistas Nacionales e Internacionales y la sala del terror. El asistir a presenciar estas figuras y leer los textos sobre sus obras y acciones, se adentra a un breve repaso de Historia de México, apoyada con pinturas y escenografía de época y el impresionante realismo de los héroes, así como de los artistas famosos de época como de actualidad. En México hay tres museos de cera: uno en la Ciudad de México, otro en Guadalajara y un tercero en la ciudad de Tijuana. Considerado como el segundo de su tipo en toda Latinoamérica, con más de 80 réplicas de personajes históricos, artistas y leyendas del cine y la televisión. Cuenta con diez salas distribuidas en cuatro áreas temáticas: Época prehispánica de México, periodo misionero de Baja California e historia de Tijuana, héroes de México, leyendas, historias; en ellas pueden verse réplicas de personajes históricos como Hidalgo, Moctezuma, Zapata, J.F. Kennedy, Gandhi o Juan Pablo II y también de ídolos del espectáculo: Cantinflas, Marilyn Monroe, Pedro Infante, Elvis Presley… No falta un rincón para pasar miedo. En una mazamorra, casi a oscuras, se encuentran los personajes clásicos del terror, como Drácula, Freddy Kruger y el Hombre Lobo.',
    'Ubicado sobre la calle 5ta, podras encontrar un sin fín de establecimientos dedicados a la venta de flores y arreglos para toda ocasión. ',
    'Es uno de los espacios más antiguos en Tijuana y que dio sus orígenes a lo que es hoy en día, la calle Primera y Ave. Revolución. Aquí es donde se conformó el primer cuadro del poblado de Tijuana. Actualmente caminar por esta plaza, es como caminar por una calle decorada durante una kermes en un pueblo mexicano, rodeado de pequeños comercios, restaurantes de comida mexicana,  kioskos que muestran parte de una artesanía popular al aire libre, mariachis que tocan armoniosos, y sus bares que invitar a deleitar una fría cerveza.',
    'Esta paramunicipal busca  ser un puente entre los artistas y los tijuanenses, asi como ofrecer espacios y actividades culturales para el disfrute de la ciudadania en general. Ademas, es la encargada de las casas de la cultura, las bibliotecas municipales, el museo de historia, entre otros. Dentro de este establecimiento se articulan actividades para la sociedad en las cuales se fomente el patrimonio cultural y artístico del municipio.',
    'Deléitate con una vasta oferta de las mejores golosinas y dulces típicas de México en mercado El Popo, ubicado a solo una calle y media de la Ave. Revolución, principal calle y sector turístico de Tijuana. Aquí encontrarás las siempre muy coloridas piñatas mexicanas y una oferta muy interesante de quesos y especias para los amantes de la cocina.',
    'Inaugurada el 12 de diciembre de 1902, fue una pequeña construcción de madera muy típica de la época de principios del siglo XX en Tijuana, posteriormente el 12 de diciembre de 1949 se puso la primera piedra de la nueva parroquia que en 1964 fue elevada al rango de Catedral. La primera iglesia fue pequeño templo de adobe en la zona baja de la ciudad, la cual fue destruida posteriormente por las aguas del río Tijuana en 1904, por lo que se planeó realizar la construcción de un nuevo centro religioso por lo que paso por varias etapas de construcción las cuales eran suspendidas continuamente por cuestiones de presupuesto.',
    'Fundado en 1961, el mercado municipal ofrece un espacio para adquirir productos y alimentos para todo tipo de gustos. Ademas de contar con una gran variedad de productos, dentro del mismo se pueden encontrar una serie de pequeños restaurantes donde se puede degustar la gastronomia tijuanense. ',
    'El Palacio frontón Jai Alai, de estilo morisco, es uno de los edificios más antiguos de Tijuana, se comenzó a construir en 1926 y se inauguró en 1947. En el Jai Alai se jugaba la pelota vasca, deporte de origen español que al no tener competencia en la ciudad, tuvo un gran éxito. En cada temporada participaban 28 jugadores españoles, razón por la que se abrió el restaurant Chiki Jai a unos cuantos metros del Jai Alai, para atender a los pelotaris. Desde su inauguración, fue uno de los principales atractivos turísticos de la ciudad y de la frontera norte, a donde asistían turistas norteamericanos en su mayoría, así como de diferentes nacionalidades. Hoy  en día es un Centro de Espectáculos llamado El Foro, donde se realizan eventos musicales y culturales. Cuenta con sala de exposiciones, escenario, bar y taquillas.',
    'Construido sobre el predio de la antigua carcel "La Ocho", este parque ofrece todas las amenidades para pasar un rato tranquilo y sano con la familia, cuenta con areas verdes, vigilancia, fuentes interactivas, juegos infantiles y un foro, ademas cuenta con un monumento representativo de América latina, un reguilete.',
    'Mientras pasea por las tiendas de artesanías, restaurantes y cafés de la famosa Ave. Revolución,  tómese una foto en blanco y negro con un "zonkey" (un burro con rayas de cebra), una tradición turistica desde 1903.',
    'En este lugar turístico la calle cobra vida durante la noche cuando sus bares se vuelven lugares de reunión entre locales y turistas, a esta calle asisten todo tipo de personas y es el lugar ideal para la vida nocturna de la ciudad.',
  ],
  lunes: 'Lunes',
  martes: 'Martes',
  miercoles: 'Miercoles',
  jueves: 'Jueves',
  viernes: 'Viernes',
  sabado: 'Sabado',
  domingo: 'Domingo',
  horario: 'Horario',
  informacion: 'Información',
  fotos: 'Fotos',
  sitios: 'Sitios turísticos'

}